[gcp_service_account]
type = "service_account"
project_id = "arlen-personalfinance"
private_key_id = "a8b5d470e39428e0f8a9eb71383efcc217b16960"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7F/tCi3XG3QCu
lWrud/ffXRHbDnDEU9tou4r3Uu+2OlQOb8jfvWvaY82W/8UDskTT1daSrk7e7URN
lftvs6bw9aX1c7uKKLyBtvpcvaHEnmRyfFLQ1+y3tQJwxwc/0zaUMv8h1e32MwjD
LI1gEdEV9IsPjdcRkMKW47d1WSccbFc7XPYW87BnidN6xNl4vALSzgZMQj1irKsF
aPp5Q2bPTSSRS8qisuNjXfTiYNYZQdHY6/Z1Xo+pKlDRTK93inDUByEAdtKeRWc4
IqWkpsJJJuccMbWgovtQZ4jesZA7c0qeeafHSWsCnXKMDvdXS3T30TtCACr1eJjj
jhx9swFRAgMBAAECggEAECnsPT2LOVkSnAKwsFWRBq0lw8UlnPCZvhylzuRNrXLw
nCawNhRJYx7IPklunfki1SJeXWHN0pixE/rnNClTPPIcGm6bPz5xussyKh0AAtqk
VvfCt+RPwTdUNKYdTDhVOMyHGkc/Pcv+783DkQ84/yqXcQqSECRvi1W1HeBL7rqP
oePMa1XlIK1ImJbrFFrbRT2NzXnhltAaJ/UCDMf/DrVuR2YEqPXojXsbbwoIeGBG
wINa9FjLJoGw3rFm1Qw/YwMkN21qwFgmG+3s7rUrOWJrpzw2bR8I/nL2RBYTQWUE
9mWHhLemzN39RkUodFHGGBXTrmfcxVYb6IuDABrtuQKBgQDhUzvTuVRFHfSQRbsJ
D+xa14Hp3EU97ukQl/EkfIF8AOtgESh0Sji7rOVJJ3ve6uXqUINL3p74PUJgeTYM
020N47LU9EmlcrR1p8ATlggQN/9NL6Ho/aR4u98dlyG/MQIXlnocNdBabbilwxGO
pHQUVnUYTxEFlaNxZw/nX3VopwKBgQDUkFmjLGp/hG7F+JB5uO7Ht57OFKu+8jIP
zLnY+yCxQzEp1QkzfJ9XweFvUWPEV6aL5OlHOPyP8prVG6uuYFX5cYazMxOq9ysC
7CrUCl2AIEWqqzBSxUpfm627tmkNj4n11ppFNF7FrywkCSx9KKhtS+jaJPYOQtso
Fvgfy2mNRwKBgBpjP/9kldzeTDTVJblC9yAQWvODS0ycfQjncmMefZ+DEA2ZFM7B
nnFEJznw+M27Xp+ZPDcXZDCYI/zeVRkdbYkR4HCWB0Xr7/xTX+grSthzZl/os2Jw
yeElx1RUzavxVlhi0/wXxUXB0bz/4j99PObg1Se6orivtItkUXV8NWjDAoGBAJZG
JtjRAcl82sNi4uDq+QSAr+iJfJHVr8azuX/IqmgnVI56abLYm93y12lXZOzd+oRU
JQeRJhyuKwAWO91fheh/dfciWPk5HFNIm06ktU1rg1URCWy6xcWpzb0zTDmmDKac
PRxH1ehz2wTu52DkaY47aDcwgjO62C0Tb/8qU0jpAoGAVPaNjbO7jvRjvtJRR/lD
VcCa8rO9K4DrHgdBjhmCJJdr8Qu3ayo3/oJ/1skl0QCOtSNtOzn08opmO/OH24C5
S2Rp7obiIRxZqEttOrT/7GqeKBnOAzCpiwDtco+wjWYfSSksPwMHEnuPmEoqsefo
h9XeZ8O3zUkkfcEP2FcGyPo=
-----END PRIVATE KEY-----"""
client_email = "arlenpersonalfinance@arlen-personalfinance.iam.gserviceaccount.com"
client_id = "107471613524076973764"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/arlenpersonalfinance%40arlen-personalfinance.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
spreadsheet_id = "1PAgc4t9RBbPLpnsoWbC1rgcwH6bX6jK8IcGel-b4cG4"